#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

OS_ARCH_LINUX="amd64 arm64"

mkdir -p output/bin
if [ -n "$DRONE_TAG" ]; then
    TAG=$DRONE_TAG
fi

cat <<EOF >"${KUBE_GIT_VERSION_FILE}"
KUBE_GIT_COMMIT=${COMMIT}
KUBE_GIT_TREE_STATE=${GIT_TREE_STATE}
KUBE_GIT_VERSION=${VERSION}
KUBE_GIT_MAJOR=${MAJOR_VERSION:1}
KUBE_GIT_MINOR=${MINOR_VERSION}
EOF

for ARCH in ${OS_ARCH_LINUX}; do
        echo Building kubelet-$ARCH
        build/run.sh make kubelet KUBE_BUILD_PLATFORMS=linux/$ARCH
	mv _output/dockerized/bin/linux/$ARCH/kubelet . 
        tar -cvzf output/bin/kubelet-$TAG-$ARCH.tar.gz kubelet && rm kubelet
done

rm -rf _output/

echo Built ${TAG}
